var configHTML = [
  '<!DOCTYPE html>',
  '<html lang="en">',
  '<head>',
  '  <meta charset="utf-8">',
  '  <title>Settings</title>',
  '  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">',
  '  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">',
  '</head>',
  '<body>',
  '<div class="container">',
  '  <header><h1>Settings</h1></header>',
  '  <form id="config" role="form" class="input-lg">',

  '    <fieldset><legend>&#9680; Invert colors</legend>',
  '      <div class="checkbox"><label>',
  '        <input type="checkbox" name="invert" value="yes"> Enable',
  '      </label></div>',
  '    </fieldset>',

  '    <fieldset><legend>&#8645; Show date on shake</legend>',
  '      <div class="checkbox"><label>',
  '        <input type="checkbox" name="show_date" value="yes" checked> Enable',
  '      </label></div>',
  '    </fieldset>',

  '    <fieldset><legend>&#9684; Date view timeout</legend>',
  '      <div class="radio"><label><input type="radio" name="date_timeout" value="3s"> 3 seconds</label></div>',
  '      <div class="radio"><label><input type="radio" name="date_timeout" value="5s"> 5 seconds</label></div>',
  '      <div class="radio"><label><input type="radio" name="date_timeout" value="8s"> 8 seconds</label></div>',
  '      <div class="radio"><label><input type="radio" name="date_timeout" value="1min" checked> 1 minute</label></div>',
  '      <div class="radio"><label><input type="radio" name="date_timeout" value="never"> Never (manual)</label></div>',
  '    </fieldset>',

  '    <fieldset><legend>&#8644; Text align</legend>',
  '      <div class="radio"><label><input type="radio" name="align" value="center" checked> &#8596; Center</label></div>',
  '      <div class="radio"><label><input type="radio" name="align" value="left"> &#8592; Left</label></div>',
  '      <div class="radio"><label><input type="radio" name="align" value="right"> &#8594; Right</label></div>',
  '    </fieldset>',

  '    <fieldset><legend>&#9698; Font size</legend>',
  '      <div class="radio"><label><input type="radio" name="font_size" value="large"> L &mdash; Large</label></div>',
  '      <div class="radio"><label><input type="radio" name="font_size" value="medium" checked> M &mdash; Medium</label></div>',
  '      <div class="radio"><label><input type="radio" name="font_size" value="small"> S &mdash; Small</label></div>',
  '    </fieldset>',

  '    <fieldset><legend>&#8853; Language</legend>',
  '      <select name="lang" class="form-control input-lg">',
  '        <option value="de">Deutsch</option>',
  '        <option value="en_GB">English (Great Britain)</option>',
  '        <option value="en_US">English (United States)</option>',
  '        <option value="es">Espa&#241;ol</option>',
  '        <option value="fr">Fran&#231;ais</option>',
  '        <option value="nl">Nederlands</option>',
  '        <option value="pt">Portugu&#234;s</option>',
  '        <option value="sv">Svenska</option>',
  '      </select>',
  '    </fieldset>',

  '    <fieldset>',
  '      <br/><a href="pebblejs://close" class="btn btn-lg btn-default">Cancel</a>',
  '      <button type="button" class="btn btn-lg btn-primary" id="b-submit">Save</button>',
  '    </fieldset>',
  '  </form>',
  '</div>',

  '<script>',
  'function getParam(k) {',
  '  var val;',
  '  window.location.hash.replace(/(?:^|[#&])([a-z_]+)=([^&]+)/ig, function(_, key, v) {',
  '    if (k === key) val = decodeURIComponent(v);',
  '  });',
  '  return val;',
  '}',

  'function saveOptions() {',
  '  var p = {};',
  '  var els = document.getElementById("config").elements;',
  '  for (var i = 0; i < els.length; i++) {',
  '    var el = els[i];',
  '    if ((el.type === "radio" || el.type === "checkbox") && !el.checked) continue;',
  '    if (el.name) p[el.name] = el.value;',
  '  }',
  '  return {',
  '    invert:       p.invert === "yes",',
  '    show_date:    p.show_date === "yes",',
  '    date_timeout: p.date_timeout || "1min",',
  '    text_align:   p.align || "center",',
  '    font_size:    p.font_size || "large",',
  '    lang:         p.lang',
  '  };',
  '}',

  'function setRadio(name, value) {',
  '  var radios = document.querySelectorAll("[name=" + name + "]");',
  '  for (var i = 0; i < radios.length; i++) {',
  '    radios[i].checked = (radios[i].value === value);',
  '  }',
  '}',

  'function applyOptions() {',
  '  var o = JSON.parse(getParam("options") || "{}");',
  '  if (o.invert === true || o.invert === "yes")',
  '    document.querySelector("[name=invert]").checked = true;',
  '  if (o.show_date === false || o.show_date === "no")',
  '    document.querySelector("[name=show_date]").checked = false;',
  '  if (o.date_timeout) setRadio("date_timeout", o.date_timeout);',
  '  if (o.text_align)   setRadio("align", o.text_align);',
  '  if (o.font_size)    setRadio("font_size", o.font_size);',
  '  if (o.lang)         document.querySelector("[name=lang]").value = o.lang;',
  '}',

  'document.getElementById("b-submit").addEventListener("click", function() {',
  '  document.location = "pebblejs://close#" + encodeURIComponent(JSON.stringify(saveOptions()));',
  '});',
  'applyOptions();',
  '<\/script>',
  '</body>',
  '</html>'
].join('\n');
